POST http://localhost:3000/signup
content-type: application/json

{
    "email": "luan@gmail.com",
    "name": "luan vieira",
    "cpf": "87748248800",
    "isDriver": true,
    // "isPassenger": true,
    "carPlate": "ABC1234"
}
